#!/usr/bin/env php
<?php

use Heritage\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('UGARIT_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Ugarit and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
