<?php

declare(strict_types=1);

namespace Ugarit\Artifacts\Geography\Database\Seeders;

use Heritage\Database\Seeder;
use Ugarit\Artifacts\Geography\Models\Country;

/**
 * Class CountrySeeder
 *
 * Seeds all recognized sovereign world countries with ISO-3166 codes, dial codes,
 * currencies, and bilingual nomenclature. In accordance with system policy, only
 * Palestine is set as active by default, while all other world nations are initialized
 * as inactive pending operational configuration.
 */
class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $countries = [
            [
                'name' => [
                    'en' => 'Palestine',
                    'ar' => 'فلسطين',
                ],
                'iso_alpha_2' => 'PS',
                'iso_alpha_3' => 'PSE',
                'dial_code' => '+970',
                'currency_code' => 'ILS',
                'flag_emoji' => '🇵🇸',
                'is_active' => true,
            ],
            [
                'name' => [
                    'en' => 'Afghanistan',
                    'ar' => 'أفغانستان',
                ],
                'iso_alpha_2' => 'AF',
                'iso_alpha_3' => 'AFG',
                'dial_code' => '+93',
                'currency_code' => 'AFN',
                'flag_emoji' => '🇦🇫',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Albania',
                    'ar' => 'ألبانيا',
                ],
                'iso_alpha_2' => 'AL',
                'iso_alpha_3' => 'ALB',
                'dial_code' => '+355',
                'currency_code' => 'ALL',
                'flag_emoji' => '🇦🇱',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Algeria',
                    'ar' => 'الجزائر',
                ],
                'iso_alpha_2' => 'DZ',
                'iso_alpha_3' => 'DZA',
                'dial_code' => '+213',
                'currency_code' => 'DZD',
                'flag_emoji' => '🇩🇿',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Andorra',
                    'ar' => 'أندورا',
                ],
                'iso_alpha_2' => 'AD',
                'iso_alpha_3' => 'AND',
                'dial_code' => '+376',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇦🇩',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Angola',
                    'ar' => 'أنغولا',
                ],
                'iso_alpha_2' => 'AO',
                'iso_alpha_3' => 'AGO',
                'dial_code' => '+244',
                'currency_code' => 'AOA',
                'flag_emoji' => '🇦🇴',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Antigua and Barbuda',
                    'ar' => 'أنتيغوا وبربودا',
                ],
                'iso_alpha_2' => 'AG',
                'iso_alpha_3' => 'ATG',
                'dial_code' => '+1-268',
                'currency_code' => 'XCD',
                'flag_emoji' => '🇦🇬',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Argentina',
                    'ar' => 'الأرجنتين',
                ],
                'iso_alpha_2' => 'AR',
                'iso_alpha_3' => 'ARG',
                'dial_code' => '+54',
                'currency_code' => 'ARS',
                'flag_emoji' => '🇦🇷',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Armenia',
                    'ar' => 'أرمينيا',
                ],
                'iso_alpha_2' => 'AM',
                'iso_alpha_3' => 'ARM',
                'dial_code' => '+374',
                'currency_code' => 'AMD',
                'flag_emoji' => '🇦🇲',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Australia',
                    'ar' => 'أستراليا',
                ],
                'iso_alpha_2' => 'AU',
                'iso_alpha_3' => 'AUS',
                'dial_code' => '+61',
                'currency_code' => 'AUD',
                'flag_emoji' => '🇦🇺',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Austria',
                    'ar' => 'النمسا',
                ],
                'iso_alpha_2' => 'AT',
                'iso_alpha_3' => 'AUT',
                'dial_code' => '+43',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇦🇹',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Azerbaijan',
                    'ar' => 'أذربيجان',
                ],
                'iso_alpha_2' => 'AZ',
                'iso_alpha_3' => 'AZE',
                'dial_code' => '+994',
                'currency_code' => 'AZN',
                'flag_emoji' => '🇦🇿',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Bahamas',
                    'ar' => 'البهاما',
                ],
                'iso_alpha_2' => 'BS',
                'iso_alpha_3' => 'BHS',
                'dial_code' => '+1-242',
                'currency_code' => 'BSD',
                'flag_emoji' => '🇧🇸',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Bahrain',
                    'ar' => 'البحرين',
                ],
                'iso_alpha_2' => 'BH',
                'iso_alpha_3' => 'BHR',
                'dial_code' => '+973',
                'currency_code' => 'BHD',
                'flag_emoji' => '🇧🇭',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Bangladesh',
                    'ar' => 'بنغلاديش',
                ],
                'iso_alpha_2' => 'BD',
                'iso_alpha_3' => 'BGD',
                'dial_code' => '+880',
                'currency_code' => 'BDT',
                'flag_emoji' => '🇧🇩',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Barbados',
                    'ar' => 'باربادوس',
                ],
                'iso_alpha_2' => 'BB',
                'iso_alpha_3' => 'BRB',
                'dial_code' => '+1-246',
                'currency_code' => 'BBD',
                'flag_emoji' => '🇧🇧',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Belarus',
                    'ar' => 'بيلاروس',
                ],
                'iso_alpha_2' => 'BY',
                'iso_alpha_3' => 'BLR',
                'dial_code' => '+375',
                'currency_code' => 'BYN',
                'flag_emoji' => '🇧🇾',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Belgium',
                    'ar' => 'بلجيكا',
                ],
                'iso_alpha_2' => 'BE',
                'iso_alpha_3' => 'BEL',
                'dial_code' => '+32',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇧🇪',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Belize',
                    'ar' => 'بليز',
                ],
                'iso_alpha_2' => 'BZ',
                'iso_alpha_3' => 'BLZ',
                'dial_code' => '+501',
                'currency_code' => 'BZD',
                'flag_emoji' => '🇧🇿',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Benin',
                    'ar' => 'بنين',
                ],
                'iso_alpha_2' => 'BJ',
                'iso_alpha_3' => 'BEN',
                'dial_code' => '+229',
                'currency_code' => 'XOF',
                'flag_emoji' => '🇧🇯',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Bhutan',
                    'ar' => 'بوتان',
                ],
                'iso_alpha_2' => 'BT',
                'iso_alpha_3' => 'BTN',
                'dial_code' => '+975',
                'currency_code' => 'BTN',
                'flag_emoji' => '🇧🇹',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Bolivia',
                    'ar' => 'بوليفيا',
                ],
                'iso_alpha_2' => 'BO',
                'iso_alpha_3' => 'BOL',
                'dial_code' => '+591',
                'currency_code' => 'BOB',
                'flag_emoji' => '🇧🇴',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Bosnia and Herzegovina',
                    'ar' => 'البوسنة والهرسك',
                ],
                'iso_alpha_2' => 'BA',
                'iso_alpha_3' => 'BIH',
                'dial_code' => '+387',
                'currency_code' => 'BAM',
                'flag_emoji' => '🇧🇦',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Botswana',
                    'ar' => 'بوتسوانا',
                ],
                'iso_alpha_2' => 'BW',
                'iso_alpha_3' => 'BWA',
                'dial_code' => '+267',
                'currency_code' => 'BWP',
                'flag_emoji' => '🇧🇼',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Brazil',
                    'ar' => 'البرازيل',
                ],
                'iso_alpha_2' => 'BR',
                'iso_alpha_3' => 'BRA',
                'dial_code' => '+55',
                'currency_code' => 'BRL',
                'flag_emoji' => '🇧🇷',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Brunei',
                    'ar' => 'بروناي',
                ],
                'iso_alpha_2' => 'BN',
                'iso_alpha_3' => 'BRN',
                'dial_code' => '+673',
                'currency_code' => 'BND',
                'flag_emoji' => '🇧🇳',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Bulgaria',
                    'ar' => 'بلغاريا',
                ],
                'iso_alpha_2' => 'BG',
                'iso_alpha_3' => 'BGR',
                'dial_code' => '+359',
                'currency_code' => 'BGN',
                'flag_emoji' => '🇧🇬',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Burkina Faso',
                    'ar' => 'بوركينا فاسو',
                ],
                'iso_alpha_2' => 'BF',
                'iso_alpha_3' => 'BFA',
                'dial_code' => '+226',
                'currency_code' => 'XOF',
                'flag_emoji' => '🇧🇫',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Burundi',
                    'ar' => 'بوروندي',
                ],
                'iso_alpha_2' => 'BI',
                'iso_alpha_3' => 'BDI',
                'dial_code' => '+257',
                'currency_code' => 'BIF',
                'flag_emoji' => '🇧🇮',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Cabo Verde',
                    'ar' => 'الرأس الأخضر',
                ],
                'iso_alpha_2' => 'CV',
                'iso_alpha_3' => 'CPV',
                'dial_code' => '+238',
                'currency_code' => 'CVE',
                'flag_emoji' => '🇨🇻',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Cambodia',
                    'ar' => 'كمبوديا',
                ],
                'iso_alpha_2' => 'KH',
                'iso_alpha_3' => 'KHM',
                'dial_code' => '+855',
                'currency_code' => 'KHR',
                'flag_emoji' => '🇰🇭',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Cameroon',
                    'ar' => 'الكاميرون',
                ],
                'iso_alpha_2' => 'CM',
                'iso_alpha_3' => 'CMR',
                'dial_code' => '+237',
                'currency_code' => 'XAF',
                'flag_emoji' => '🇨🇲',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Canada',
                    'ar' => 'كندا',
                ],
                'iso_alpha_2' => 'CA',
                'iso_alpha_3' => 'CAN',
                'dial_code' => '+1',
                'currency_code' => 'CAD',
                'flag_emoji' => '🇨🇦',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Central African Republic',
                    'ar' => 'جمهورية أفريقيا الوسطى',
                ],
                'iso_alpha_2' => 'CF',
                'iso_alpha_3' => 'CAF',
                'dial_code' => '+236',
                'currency_code' => 'XAF',
                'flag_emoji' => '🇨🇫',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Chad',
                    'ar' => 'تشاد',
                ],
                'iso_alpha_2' => 'TD',
                'iso_alpha_3' => 'TCD',
                'dial_code' => '+235',
                'currency_code' => 'XAF',
                'flag_emoji' => '🇹🇩',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Chile',
                    'ar' => 'تشيلي',
                ],
                'iso_alpha_2' => 'CL',
                'iso_alpha_3' => 'CHL',
                'dial_code' => '+56',
                'currency_code' => 'CLP',
                'flag_emoji' => '🇨🇱',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'China',
                    'ar' => 'الصين',
                ],
                'iso_alpha_2' => 'CN',
                'iso_alpha_3' => 'CHN',
                'dial_code' => '+86',
                'currency_code' => 'CNY',
                'flag_emoji' => '🇨🇳',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Colombia',
                    'ar' => 'كولومبيا',
                ],
                'iso_alpha_2' => 'CO',
                'iso_alpha_3' => 'COL',
                'dial_code' => '+57',
                'currency_code' => 'COP',
                'flag_emoji' => '🇨🇴',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Comoros',
                    'ar' => 'جزر القمر',
                ],
                'iso_alpha_2' => 'KM',
                'iso_alpha_3' => 'COM',
                'dial_code' => '+269',
                'currency_code' => 'KMF',
                'flag_emoji' => '🇰🇲',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Congo, Democratic Republic of the',
                    'ar' => 'جمهورية الكونغو الديمقراطية',
                ],
                'iso_alpha_2' => 'CD',
                'iso_alpha_3' => 'COD',
                'dial_code' => '+243',
                'currency_code' => 'CDF',
                'flag_emoji' => '🇨🇩',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Congo, Republic of the',
                    'ar' => 'جمهورية الكونغو',
                ],
                'iso_alpha_2' => 'CG',
                'iso_alpha_3' => 'COG',
                'dial_code' => '+242',
                'currency_code' => 'XAF',
                'flag_emoji' => '🇨🇬',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Costa Rica',
                    'ar' => 'كوستاريكا',
                ],
                'iso_alpha_2' => 'CR',
                'iso_alpha_3' => 'CRI',
                'dial_code' => '+506',
                'currency_code' => 'CRC',
                'flag_emoji' => '🇨🇷',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Cote d\'Ivoire',
                    'ar' => 'ساحل العاج',
                ],
                'iso_alpha_2' => 'CI',
                'iso_alpha_3' => 'CIV',
                'dial_code' => '+225',
                'currency_code' => 'XOF',
                'flag_emoji' => '🇨🇮',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Croatia',
                    'ar' => 'كرواتيا',
                ],
                'iso_alpha_2' => 'HR',
                'iso_alpha_3' => 'HRV',
                'dial_code' => '+385',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇭🇷',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Cuba',
                    'ar' => 'كوبا',
                ],
                'iso_alpha_2' => 'CU',
                'iso_alpha_3' => 'CUB',
                'dial_code' => '+53',
                'currency_code' => 'CUP',
                'flag_emoji' => '🇨🇺',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Cyprus',
                    'ar' => 'قبرص',
                ],
                'iso_alpha_2' => 'CY',
                'iso_alpha_3' => 'CYP',
                'dial_code' => '+357',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇨🇾',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Czech Republic',
                    'ar' => 'التشيك',
                ],
                'iso_alpha_2' => 'CZ',
                'iso_alpha_3' => 'CZE',
                'dial_code' => '+420',
                'currency_code' => 'CZK',
                'flag_emoji' => '🇨🇿',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Denmark',
                    'ar' => 'الدنمارك',
                ],
                'iso_alpha_2' => 'DK',
                'iso_alpha_3' => 'DNK',
                'dial_code' => '+45',
                'currency_code' => 'DKK',
                'flag_emoji' => '🇩🇰',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Djibouti',
                    'ar' => 'جيبوتي',
                ],
                'iso_alpha_2' => 'DJ',
                'iso_alpha_3' => 'DJI',
                'dial_code' => '+253',
                'currency_code' => 'DJF',
                'flag_emoji' => '🇩🇯',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Dominica',
                    'ar' => 'دومينيكا',
                ],
                'iso_alpha_2' => 'DM',
                'iso_alpha_3' => 'DMA',
                'dial_code' => '+1-767',
                'currency_code' => 'XCD',
                'flag_emoji' => '🇩🇲',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Dominican Republic',
                    'ar' => 'جمهورية الدومينيكان',
                ],
                'iso_alpha_2' => 'DO',
                'iso_alpha_3' => 'DOM',
                'dial_code' => '+1-809',
                'currency_code' => 'DOP',
                'flag_emoji' => '🇩🇴',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Ecuador',
                    'ar' => 'الإكوادور',
                ],
                'iso_alpha_2' => 'EC',
                'iso_alpha_3' => 'ECU',
                'dial_code' => '+593',
                'currency_code' => 'USD',
                'flag_emoji' => '🇪🇨',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Egypt',
                    'ar' => 'مصر',
                ],
                'iso_alpha_2' => 'EG',
                'iso_alpha_3' => 'EGY',
                'dial_code' => '+20',
                'currency_code' => 'EGP',
                'flag_emoji' => '🇪🇬',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'El Salvador',
                    'ar' => 'السلفادور',
                ],
                'iso_alpha_2' => 'SV',
                'iso_alpha_3' => 'SLV',
                'dial_code' => '+503',
                'currency_code' => 'USD',
                'flag_emoji' => '🇸🇻',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Equatorial Guinea',
                    'ar' => 'غينيا الاستوائية',
                ],
                'iso_alpha_2' => 'GQ',
                'iso_alpha_3' => 'GNQ',
                'dial_code' => '+240',
                'currency_code' => 'XAF',
                'flag_emoji' => '🇬🇶',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Eritrea',
                    'ar' => 'إريتريا',
                ],
                'iso_alpha_2' => 'ER',
                'iso_alpha_3' => 'ERI',
                'dial_code' => '+291',
                'currency_code' => 'ERN',
                'flag_emoji' => '🇪🇷',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Estonia',
                    'ar' => 'إستونيا',
                ],
                'iso_alpha_2' => 'EE',
                'iso_alpha_3' => 'EST',
                'dial_code' => '+372',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇪🇪',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Eswatini',
                    'ar' => 'إسواتيني',
                ],
                'iso_alpha_2' => 'SZ',
                'iso_alpha_3' => 'SWZ',
                'dial_code' => '+268',
                'currency_code' => 'SZL',
                'flag_emoji' => '🇸🇿',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Ethiopia',
                    'ar' => 'إثيوبيا',
                ],
                'iso_alpha_2' => 'ET',
                'iso_alpha_3' => 'ETH',
                'dial_code' => '+251',
                'currency_code' => 'ETB',
                'flag_emoji' => '🇪🇹',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Fiji',
                    'ar' => 'فيجي',
                ],
                'iso_alpha_2' => 'FJ',
                'iso_alpha_3' => 'FJI',
                'dial_code' => '+679',
                'currency_code' => 'FJD',
                'flag_emoji' => '🇫🇯',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Finland',
                    'ar' => 'فنلندا',
                ],
                'iso_alpha_2' => 'FI',
                'iso_alpha_3' => 'FIN',
                'dial_code' => '+358',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇫🇮',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'France',
                    'ar' => 'فرنسا',
                ],
                'iso_alpha_2' => 'FR',
                'iso_alpha_3' => 'FRA',
                'dial_code' => '+33',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇫🇷',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Gabon',
                    'ar' => 'الغابون',
                ],
                'iso_alpha_2' => 'GA',
                'iso_alpha_3' => 'GAB',
                'dial_code' => '+241',
                'currency_code' => 'XAF',
                'flag_emoji' => '🇬🇦',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Gambia',
                    'ar' => 'غامبيا',
                ],
                'iso_alpha_2' => 'GM',
                'iso_alpha_3' => 'GMB',
                'dial_code' => '+220',
                'currency_code' => 'GMD',
                'flag_emoji' => '🇬🇲',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Georgia',
                    'ar' => 'جورجيا',
                ],
                'iso_alpha_2' => 'GE',
                'iso_alpha_3' => 'GEO',
                'dial_code' => '+995',
                'currency_code' => 'GEL',
                'flag_emoji' => '🇬🇪',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Germany',
                    'ar' => 'ألمانيا',
                ],
                'iso_alpha_2' => 'DE',
                'iso_alpha_3' => 'DEU',
                'dial_code' => '+49',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇩🇪',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Ghana',
                    'ar' => 'غانا',
                ],
                'iso_alpha_2' => 'GH',
                'iso_alpha_3' => 'GHA',
                'dial_code' => '+233',
                'currency_code' => 'GHS',
                'flag_emoji' => '🇬🇭',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Greece',
                    'ar' => 'اليونان',
                ],
                'iso_alpha_2' => 'GR',
                'iso_alpha_3' => 'GRC',
                'dial_code' => '+30',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇬🇷',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Grenada',
                    'ar' => 'غرينادا',
                ],
                'iso_alpha_2' => 'GD',
                'iso_alpha_3' => 'GRD',
                'dial_code' => '+1-473',
                'currency_code' => 'XCD',
                'flag_emoji' => '🇬🇩',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Guatemala',
                    'ar' => 'غواتيمالا',
                ],
                'iso_alpha_2' => 'GT',
                'iso_alpha_3' => 'GTM',
                'dial_code' => '+502',
                'currency_code' => 'GTQ',
                'flag_emoji' => '🇬🇹',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Guinea',
                    'ar' => 'غينيا',
                ],
                'iso_alpha_2' => 'GN',
                'iso_alpha_3' => 'GIN',
                'dial_code' => '+224',
                'currency_code' => 'GNF',
                'flag_emoji' => '🇬🇳',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Guinea-Bissau',
                    'ar' => 'غينيا بيساو',
                ],
                'iso_alpha_2' => 'GW',
                'iso_alpha_3' => 'GNB',
                'dial_code' => '+245',
                'currency_code' => 'XOF',
                'flag_emoji' => '🇬🇼',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Guyana',
                    'ar' => 'غيانا',
                ],
                'iso_alpha_2' => 'GY',
                'iso_alpha_3' => 'GUY',
                'dial_code' => '+592',
                'currency_code' => 'GYD',
                'flag_emoji' => '🇬🇾',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Haiti',
                    'ar' => 'هايتي',
                ],
                'iso_alpha_2' => 'HT',
                'iso_alpha_3' => 'HTI',
                'dial_code' => '+509',
                'currency_code' => 'HTG',
                'flag_emoji' => '🇭🇹',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Honduras',
                    'ar' => 'هندوراس',
                ],
                'iso_alpha_2' => 'HN',
                'iso_alpha_3' => 'HND',
                'dial_code' => '+504',
                'currency_code' => 'HNL',
                'flag_emoji' => '🇭🇳',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Hungary',
                    'ar' => 'المجر',
                ],
                'iso_alpha_2' => 'HU',
                'iso_alpha_3' => 'HUN',
                'dial_code' => '+36',
                'currency_code' => 'HUF',
                'flag_emoji' => '🇭🇺',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Iceland',
                    'ar' => 'آيسلندا',
                ],
                'iso_alpha_2' => 'IS',
                'iso_alpha_3' => 'ISL',
                'dial_code' => '+354',
                'currency_code' => 'ISK',
                'flag_emoji' => '🇮🇸',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'India',
                    'ar' => 'الهند',
                ],
                'iso_alpha_2' => 'IN',
                'iso_alpha_3' => 'IND',
                'dial_code' => '+91',
                'currency_code' => 'INR',
                'flag_emoji' => '🇮🇳',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Indonesia',
                    'ar' => 'إندونيسيا',
                ],
                'iso_alpha_2' => 'ID',
                'iso_alpha_3' => 'IDN',
                'dial_code' => '+62',
                'currency_code' => 'IDR',
                'flag_emoji' => '🇮🇩',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Iran',
                    'ar' => 'إيران',
                ],
                'iso_alpha_2' => 'IR',
                'iso_alpha_3' => 'IRN',
                'dial_code' => '+98',
                'currency_code' => 'IRR',
                'flag_emoji' => '🇮🇷',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Iraq',
                    'ar' => 'العراق',
                ],
                'iso_alpha_2' => 'IQ',
                'iso_alpha_3' => 'IRQ',
                'dial_code' => '+964',
                'currency_code' => 'IQD',
                'flag_emoji' => '🇮🇶',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Ireland',
                    'ar' => 'أيرلندا',
                ],
                'iso_alpha_2' => 'IE',
                'iso_alpha_3' => 'IRL',
                'dial_code' => '+353',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇮🇪',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Italy',
                    'ar' => 'إيطاليا',
                ],
                'iso_alpha_2' => 'IT',
                'iso_alpha_3' => 'ITA',
                'dial_code' => '+39',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇮🇹',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Jamaica',
                    'ar' => 'جامايكا',
                ],
                'iso_alpha_2' => 'JM',
                'iso_alpha_3' => 'JAM',
                'dial_code' => '+1-876',
                'currency_code' => 'JMD',
                'flag_emoji' => '🇯🇲',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Japan',
                    'ar' => 'اليابان',
                ],
                'iso_alpha_2' => 'JP',
                'iso_alpha_3' => 'JPN',
                'dial_code' => '+81',
                'currency_code' => 'JPY',
                'flag_emoji' => '🇯🇵',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Jordan',
                    'ar' => 'الأردن',
                ],
                'iso_alpha_2' => 'JO',
                'iso_alpha_3' => 'JOR',
                'dial_code' => '+962',
                'currency_code' => 'JOD',
                'flag_emoji' => '🇯🇴',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Kazakhstan',
                    'ar' => 'كازاخستان',
                ],
                'iso_alpha_2' => 'KZ',
                'iso_alpha_3' => 'KAZ',
                'dial_code' => '+7',
                'currency_code' => 'KZT',
                'flag_emoji' => '🇰🇿',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Kenya',
                    'ar' => 'كينيا',
                ],
                'iso_alpha_2' => 'KE',
                'iso_alpha_3' => 'KEN',
                'dial_code' => '+254',
                'currency_code' => 'KES',
                'flag_emoji' => '🇰🇪',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Kiribati',
                    'ar' => 'كيريباتي',
                ],
                'iso_alpha_2' => 'KI',
                'iso_alpha_3' => 'KIR',
                'dial_code' => '+686',
                'currency_code' => 'AUD',
                'flag_emoji' => '🇰🇮',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Kuwait',
                    'ar' => 'الكويت',
                ],
                'iso_alpha_2' => 'KW',
                'iso_alpha_3' => 'KWT',
                'dial_code' => '+965',
                'currency_code' => 'KWD',
                'flag_emoji' => '🇰🇼',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Kyrgyzstan',
                    'ar' => 'قيرغيزستان',
                ],
                'iso_alpha_2' => 'KG',
                'iso_alpha_3' => 'KGZ',
                'dial_code' => '+996',
                'currency_code' => 'KGS',
                'flag_emoji' => '🇰🇬',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Laos',
                    'ar' => 'لاوس',
                ],
                'iso_alpha_2' => 'LA',
                'iso_alpha_3' => 'LAO',
                'dial_code' => '+856',
                'currency_code' => 'LAK',
                'flag_emoji' => '🇱🇦',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Latvia',
                    'ar' => 'لاتفيا',
                ],
                'iso_alpha_2' => 'LV',
                'iso_alpha_3' => 'LVA',
                'dial_code' => '+371',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇱🇻',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Lebanon',
                    'ar' => 'لبنان',
                ],
                'iso_alpha_2' => 'LB',
                'iso_alpha_3' => 'LBN',
                'dial_code' => '+961',
                'currency_code' => 'LBP',
                'flag_emoji' => '🇱🇧',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Lesotho',
                    'ar' => 'ليسوتو',
                ],
                'iso_alpha_2' => 'LS',
                'iso_alpha_3' => 'LSO',
                'dial_code' => '+266',
                'currency_code' => 'LSL',
                'flag_emoji' => '🇱🇸',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Liberia',
                    'ar' => 'ليبيريا',
                ],
                'iso_alpha_2' => 'LR',
                'iso_alpha_3' => 'LBR',
                'dial_code' => '+231',
                'currency_code' => 'LRD',
                'flag_emoji' => '🇱🇷',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Libya',
                    'ar' => 'ليبيا',
                ],
                'iso_alpha_2' => 'LY',
                'iso_alpha_3' => 'LBY',
                'dial_code' => '+218',
                'currency_code' => 'LYD',
                'flag_emoji' => '🇱🇾',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Liechtenstein',
                    'ar' => 'ليختنشتاين',
                ],
                'iso_alpha_2' => 'LI',
                'iso_alpha_3' => 'LIE',
                'dial_code' => '+423',
                'currency_code' => 'CHF',
                'flag_emoji' => '🇱🇮',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Lithuania',
                    'ar' => 'ليتوانيا',
                ],
                'iso_alpha_2' => 'LT',
                'iso_alpha_3' => 'LTU',
                'dial_code' => '+370',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇱🇹',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Luxembourg',
                    'ar' => 'لوكسمبورغ',
                ],
                'iso_alpha_2' => 'LU',
                'iso_alpha_3' => 'LUX',
                'dial_code' => '+352',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇱🇺',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Madagascar',
                    'ar' => 'مدغشقر',
                ],
                'iso_alpha_2' => 'MG',
                'iso_alpha_3' => 'MDG',
                'dial_code' => '+261',
                'currency_code' => 'MGA',
                'flag_emoji' => '🇲🇬',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Malawi',
                    'ar' => 'مالاوي',
                ],
                'iso_alpha_2' => 'MW',
                'iso_alpha_3' => 'MWI',
                'dial_code' => '+265',
                'currency_code' => 'MWK',
                'flag_emoji' => '🇲🇼',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Malaysia',
                    'ar' => 'ماليزيا',
                ],
                'iso_alpha_2' => 'MY',
                'iso_alpha_3' => 'MYS',
                'dial_code' => '+60',
                'currency_code' => 'MYR',
                'flag_emoji' => '🇲🇾',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Maldives',
                    'ar' => 'المالديف',
                ],
                'iso_alpha_2' => 'MV',
                'iso_alpha_3' => 'MDV',
                'dial_code' => '+960',
                'currency_code' => 'MVR',
                'flag_emoji' => '🇲🇻',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Mali',
                    'ar' => 'مالي',
                ],
                'iso_alpha_2' => 'ML',
                'iso_alpha_3' => 'MLI',
                'dial_code' => '+223',
                'currency_code' => 'XOF',
                'flag_emoji' => '🇲🇱',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Malta',
                    'ar' => 'مالطا',
                ],
                'iso_alpha_2' => 'MT',
                'iso_alpha_3' => 'MLT',
                'dial_code' => '+356',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇲🇹',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Marshall Islands',
                    'ar' => 'جزر مارشال',
                ],
                'iso_alpha_2' => 'MH',
                'iso_alpha_3' => 'MHL',
                'dial_code' => '+692',
                'currency_code' => 'USD',
                'flag_emoji' => '🇲🇭',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Mauritania',
                    'ar' => 'موريتانيا',
                ],
                'iso_alpha_2' => 'MR',
                'iso_alpha_3' => 'MRT',
                'dial_code' => '+222',
                'currency_code' => 'MRU',
                'flag_emoji' => '🇲🇷',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Mauritius',
                    'ar' => 'موريشيوس',
                ],
                'iso_alpha_2' => 'MU',
                'iso_alpha_3' => 'MUS',
                'dial_code' => '+230',
                'currency_code' => 'MUR',
                'flag_emoji' => '🇲🇺',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Mexico',
                    'ar' => 'المكسيك',
                ],
                'iso_alpha_2' => 'MX',
                'iso_alpha_3' => 'MEX',
                'dial_code' => '+52',
                'currency_code' => 'MXN',
                'flag_emoji' => '🇲🇽',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Micronesia',
                    'ar' => 'ميكرونيزيا',
                ],
                'iso_alpha_2' => 'FM',
                'iso_alpha_3' => 'FSM',
                'dial_code' => '+691',
                'currency_code' => 'USD',
                'flag_emoji' => '🇫🇲',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Moldova',
                    'ar' => 'مولدوفا',
                ],
                'iso_alpha_2' => 'MD',
                'iso_alpha_3' => 'MDA',
                'dial_code' => '+373',
                'currency_code' => 'MDL',
                'flag_emoji' => '🇲🇩',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Monaco',
                    'ar' => 'موناكو',
                ],
                'iso_alpha_2' => 'MC',
                'iso_alpha_3' => 'MCO',
                'dial_code' => '+377',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇲🇨',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Mongolia',
                    'ar' => 'منغوليا',
                ],
                'iso_alpha_2' => 'MN',
                'iso_alpha_3' => 'MNG',
                'dial_code' => '+976',
                'currency_code' => 'MNT',
                'flag_emoji' => '🇲🇳',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Montenegro',
                    'ar' => 'الجبل الأسود',
                ],
                'iso_alpha_2' => 'ME',
                'iso_alpha_3' => 'MNE',
                'dial_code' => '+382',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇲🇪',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Morocco',
                    'ar' => 'المغرب',
                ],
                'iso_alpha_2' => 'MA',
                'iso_alpha_3' => 'MAR',
                'dial_code' => '+212',
                'currency_code' => 'MAD',
                'flag_emoji' => '🇲🇦',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Mozambique',
                    'ar' => 'موزمبيق',
                ],
                'iso_alpha_2' => 'MZ',
                'iso_alpha_3' => 'MOZ',
                'dial_code' => '+258',
                'currency_code' => 'MZN',
                'flag_emoji' => '🇲🇿',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Myanmar',
                    'ar' => 'ميانمار',
                ],
                'iso_alpha_2' => 'MM',
                'iso_alpha_3' => 'MMR',
                'dial_code' => '+95',
                'currency_code' => 'MMK',
                'flag_emoji' => '🇲🇲',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Namibia',
                    'ar' => 'ناميبيا',
                ],
                'iso_alpha_2' => 'NA',
                'iso_alpha_3' => 'NAM',
                'dial_code' => '+264',
                'currency_code' => 'NAD',
                'flag_emoji' => '🇳🇦',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Nauru',
                    'ar' => 'ناورو',
                ],
                'iso_alpha_2' => 'NR',
                'iso_alpha_3' => 'NRU',
                'dial_code' => '+674',
                'currency_code' => 'AUD',
                'flag_emoji' => '🇳🇷',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Nepal',
                    'ar' => 'نيبال',
                ],
                'iso_alpha_2' => 'NP',
                'iso_alpha_3' => 'NPL',
                'dial_code' => '+977',
                'currency_code' => 'NPR',
                'flag_emoji' => '🇳🇵',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Netherlands',
                    'ar' => 'هولندا',
                ],
                'iso_alpha_2' => 'NL',
                'iso_alpha_3' => 'NLD',
                'dial_code' => '+31',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇳🇱',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'New Zealand',
                    'ar' => 'نيوزيلندا',
                ],
                'iso_alpha_2' => 'NZ',
                'iso_alpha_3' => 'NZL',
                'dial_code' => '+64',
                'currency_code' => 'NZD',
                'flag_emoji' => '🇳🇿',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Nicaragua',
                    'ar' => 'نيكاراغوا',
                ],
                'iso_alpha_2' => 'NI',
                'iso_alpha_3' => 'NIC',
                'dial_code' => '+505',
                'currency_code' => 'NIO',
                'flag_emoji' => '🇳🇮',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Niger',
                    'ar' => 'النيجر',
                ],
                'iso_alpha_2' => 'NE',
                'iso_alpha_3' => 'NER',
                'dial_code' => '+227',
                'currency_code' => 'XOF',
                'flag_emoji' => '🇳🇪',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Nigeria',
                    'ar' => 'نيجيريا',
                ],
                'iso_alpha_2' => 'NG',
                'iso_alpha_3' => 'NGA',
                'dial_code' => '+234',
                'currency_code' => 'NGN',
                'flag_emoji' => '🇳🇬',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'North Korea',
                    'ar' => 'كوريا الشمالية',
                ],
                'iso_alpha_2' => 'KP',
                'iso_alpha_3' => 'PRK',
                'dial_code' => '+850',
                'currency_code' => 'KPW',
                'flag_emoji' => '🇰🇵',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'North Macedonia',
                    'ar' => 'مقدونيا الشمالية',
                ],
                'iso_alpha_2' => 'MK',
                'iso_alpha_3' => 'MKD',
                'dial_code' => '+389',
                'currency_code' => 'MKD',
                'flag_emoji' => '🇲🇰',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Norway',
                    'ar' => 'النرويج',
                ],
                'iso_alpha_2' => 'NO',
                'iso_alpha_3' => 'NOR',
                'dial_code' => '+47',
                'currency_code' => 'NOK',
                'flag_emoji' => '🇳🇴',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Oman',
                    'ar' => 'عمان',
                ],
                'iso_alpha_2' => 'OM',
                'iso_alpha_3' => 'OMN',
                'dial_code' => '+968',
                'currency_code' => 'OMR',
                'flag_emoji' => '🇴🇲',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Pakistan',
                    'ar' => 'باكستان',
                ],
                'iso_alpha_2' => 'PK',
                'iso_alpha_3' => 'PAK',
                'dial_code' => '+92',
                'currency_code' => 'PKR',
                'flag_emoji' => '🇵🇰',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Palau',
                    'ar' => 'بالاو',
                ],
                'iso_alpha_2' => 'PW',
                'iso_alpha_3' => 'PLW',
                'dial_code' => '+680',
                'currency_code' => 'USD',
                'flag_emoji' => '🇵🇼',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Panama',
                    'ar' => 'بنما',
                ],
                'iso_alpha_2' => 'PA',
                'iso_alpha_3' => 'PAN',
                'dial_code' => '+507',
                'currency_code' => 'PAB',
                'flag_emoji' => '🇵🇦',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Papua New Guinea',
                    'ar' => 'بابوا غينيا الجديدة',
                ],
                'iso_alpha_2' => 'PG',
                'iso_alpha_3' => 'PNG',
                'dial_code' => '+675',
                'currency_code' => 'PGK',
                'flag_emoji' => '🇵🇬',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Paraguay',
                    'ar' => 'باراغواي',
                ],
                'iso_alpha_2' => 'PY',
                'iso_alpha_3' => 'PRY',
                'dial_code' => '+595',
                'currency_code' => 'PYG',
                'flag_emoji' => '🇵🇾',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Peru',
                    'ar' => 'بيرو',
                ],
                'iso_alpha_2' => 'PE',
                'iso_alpha_3' => 'PER',
                'dial_code' => '+51',
                'currency_code' => 'PEN',
                'flag_emoji' => '🇵🇪',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Philippines',
                    'ar' => 'الفلبين',
                ],
                'iso_alpha_2' => 'PH',
                'iso_alpha_3' => 'PHL',
                'dial_code' => '+63',
                'currency_code' => 'PHP',
                'flag_emoji' => '🇵🇭',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Poland',
                    'ar' => 'بولندا',
                ],
                'iso_alpha_2' => 'PL',
                'iso_alpha_3' => 'POL',
                'dial_code' => '+48',
                'currency_code' => 'PLN',
                'flag_emoji' => '🇵🇱',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Portugal',
                    'ar' => 'البرتغال',
                ],
                'iso_alpha_2' => 'PT',
                'iso_alpha_3' => 'PRT',
                'dial_code' => '+351',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇵🇹',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Qatar',
                    'ar' => 'قطر',
                ],
                'iso_alpha_2' => 'QA',
                'iso_alpha_3' => 'QAT',
                'dial_code' => '+974',
                'currency_code' => 'QAR',
                'flag_emoji' => '🇶🇦',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Romania',
                    'ar' => 'رومانيا',
                ],
                'iso_alpha_2' => 'RO',
                'iso_alpha_3' => 'ROU',
                'dial_code' => '+40',
                'currency_code' => 'RON',
                'flag_emoji' => '🇷🇴',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Russia',
                    'ar' => 'روسيا',
                ],
                'iso_alpha_2' => 'RU',
                'iso_alpha_3' => 'RUS',
                'dial_code' => '+7',
                'currency_code' => 'RUB',
                'flag_emoji' => '🇷🇺',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Rwanda',
                    'ar' => 'رواندا',
                ],
                'iso_alpha_2' => 'RW',
                'iso_alpha_3' => 'RWA',
                'dial_code' => '+250',
                'currency_code' => 'RWF',
                'flag_emoji' => '🇷🇼',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Saint Kitts and Nevis',
                    'ar' => 'سانت كيتس ونيفيس',
                ],
                'iso_alpha_2' => 'KN',
                'iso_alpha_3' => 'KNA',
                'dial_code' => '+1-869',
                'currency_code' => 'XCD',
                'flag_emoji' => '🇰🇳',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Saint Lucia',
                    'ar' => 'سانت لوسيا',
                ],
                'iso_alpha_2' => 'LC',
                'iso_alpha_3' => 'LCA',
                'dial_code' => '+1-758',
                'currency_code' => 'XCD',
                'flag_emoji' => '🇱🇨',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Saint Vincent and the Grenadines',
                    'ar' => 'سانت فنسنت والغرينادين',
                ],
                'iso_alpha_2' => 'VC',
                'iso_alpha_3' => 'VCT',
                'dial_code' => '+1-784',
                'currency_code' => 'XCD',
                'flag_emoji' => '🇻🇨',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Samoa',
                    'ar' => 'ساموا',
                ],
                'iso_alpha_2' => 'WS',
                'iso_alpha_3' => 'WSM',
                'dial_code' => '+685',
                'currency_code' => 'WST',
                'flag_emoji' => '🇼🇸',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'San Marino',
                    'ar' => 'سان مارينو',
                ],
                'iso_alpha_2' => 'SM',
                'iso_alpha_3' => 'SMR',
                'dial_code' => '+378',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇸🇲',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Sao Tome and Principe',
                    'ar' => 'ساو تومي وبرينسيبي',
                ],
                'iso_alpha_2' => 'ST',
                'iso_alpha_3' => 'STP',
                'dial_code' => '+239',
                'currency_code' => 'STN',
                'flag_emoji' => '🇸🇹',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Saudi Arabia',
                    'ar' => 'المملكة العربية السعودية',
                ],
                'iso_alpha_2' => 'SA',
                'iso_alpha_3' => 'SAU',
                'dial_code' => '+966',
                'currency_code' => 'SAR',
                'flag_emoji' => '🇸🇦',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Senegal',
                    'ar' => 'السنغال',
                ],
                'iso_alpha_2' => 'SN',
                'iso_alpha_3' => 'SEN',
                'dial_code' => '+221',
                'currency_code' => 'XOF',
                'flag_emoji' => '🇸🇳',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Serbia',
                    'ar' => 'صربيا',
                ],
                'iso_alpha_2' => 'RS',
                'iso_alpha_3' => 'SRB',
                'dial_code' => '+381',
                'currency_code' => 'RSD',
                'flag_emoji' => '🇷🇸',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Seychelles',
                    'ar' => 'سيشل',
                ],
                'iso_alpha_2' => 'SC',
                'iso_alpha_3' => 'SYC',
                'dial_code' => '+248',
                'currency_code' => 'SCR',
                'flag_emoji' => '🇸🇨',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Sierra Leone',
                    'ar' => 'سيراليون',
                ],
                'iso_alpha_2' => 'SL',
                'iso_alpha_3' => 'SLE',
                'dial_code' => '+232',
                'currency_code' => 'SLL',
                'flag_emoji' => '🇸🇱',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Singapore',
                    'ar' => 'سنغافورة',
                ],
                'iso_alpha_2' => 'SG',
                'iso_alpha_3' => 'SGP',
                'dial_code' => '+65',
                'currency_code' => 'SGD',
                'flag_emoji' => '🇸🇬',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Slovakia',
                    'ar' => 'سلوفاكيا',
                ],
                'iso_alpha_2' => 'SK',
                'iso_alpha_3' => 'SVK',
                'dial_code' => '+421',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇸🇰',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Slovenia',
                    'ar' => 'سلوفينيا',
                ],
                'iso_alpha_2' => 'SI',
                'iso_alpha_3' => 'SVN',
                'dial_code' => '+386',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇸🇮',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Solomon Islands',
                    'ar' => 'جزر سليمان',
                ],
                'iso_alpha_2' => 'SB',
                'iso_alpha_3' => 'SLB',
                'dial_code' => '+677',
                'currency_code' => 'SBD',
                'flag_emoji' => '🇸🇧',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Somalia',
                    'ar' => 'الصومال',
                ],
                'iso_alpha_2' => 'SO',
                'iso_alpha_3' => 'SOM',
                'dial_code' => '+252',
                'currency_code' => 'SOS',
                'flag_emoji' => '🇸🇴',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'South Africa',
                    'ar' => 'جنوب أفريقيا',
                ],
                'iso_alpha_2' => 'ZA',
                'iso_alpha_3' => 'ZAF',
                'dial_code' => '+27',
                'currency_code' => 'ZAR',
                'flag_emoji' => '🇿🇦',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'South Korea',
                    'ar' => 'كوريا الجنوبية',
                ],
                'iso_alpha_2' => 'KR',
                'iso_alpha_3' => 'KOR',
                'dial_code' => '+82',
                'currency_code' => 'KRW',
                'flag_emoji' => '🇰🇷',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'South Sudan',
                    'ar' => 'جنوب السودان',
                ],
                'iso_alpha_2' => 'SS',
                'iso_alpha_3' => 'SSD',
                'dial_code' => '+211',
                'currency_code' => 'SSP',
                'flag_emoji' => '🇸🇸',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Spain',
                    'ar' => 'إسبانيا',
                ],
                'iso_alpha_2' => 'ES',
                'iso_alpha_3' => 'ESP',
                'dial_code' => '+34',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇪🇸',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Sri Lanka',
                    'ar' => 'سريلانكا',
                ],
                'iso_alpha_2' => 'LK',
                'iso_alpha_3' => 'LKA',
                'dial_code' => '+94',
                'currency_code' => 'LKR',
                'flag_emoji' => '🇱🇰',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Sudan',
                    'ar' => 'السودان',
                ],
                'iso_alpha_2' => 'SD',
                'iso_alpha_3' => 'SDN',
                'dial_code' => '+249',
                'currency_code' => 'SDG',
                'flag_emoji' => '🇸🇩',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Suriname',
                    'ar' => 'سورينام',
                ],
                'iso_alpha_2' => 'SR',
                'iso_alpha_3' => 'SUR',
                'dial_code' => '+597',
                'currency_code' => 'SRD',
                'flag_emoji' => '🇸🇷',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Sweden',
                    'ar' => 'السويد',
                ],
                'iso_alpha_2' => 'SE',
                'iso_alpha_3' => 'SWE',
                'dial_code' => '+46',
                'currency_code' => 'SEK',
                'flag_emoji' => '🇸🇪',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Switzerland',
                    'ar' => 'سويسرا',
                ],
                'iso_alpha_2' => 'CH',
                'iso_alpha_3' => 'CHE',
                'dial_code' => '+41',
                'currency_code' => 'CHF',
                'flag_emoji' => '🇨🇭',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Syria',
                    'ar' => 'سوريا',
                ],
                'iso_alpha_2' => 'SY',
                'iso_alpha_3' => 'SYR',
                'dial_code' => '+963',
                'currency_code' => 'SYP',
                'flag_emoji' => '🇸🇾',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Tajikistan',
                    'ar' => 'طاجيكستان',
                ],
                'iso_alpha_2' => 'TJ',
                'iso_alpha_3' => 'TJK',
                'dial_code' => '+992',
                'currency_code' => 'TJS',
                'flag_emoji' => '🇹🇯',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Tanzania',
                    'ar' => 'تنزانيا',
                ],
                'iso_alpha_2' => 'TZ',
                'iso_alpha_3' => 'TZA',
                'dial_code' => '+255',
                'currency_code' => 'TZS',
                'flag_emoji' => '🇹🇿',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Thailand',
                    'ar' => 'تايلاند',
                ],
                'iso_alpha_2' => 'TH',
                'iso_alpha_3' => 'THA',
                'dial_code' => '+66',
                'currency_code' => 'THB',
                'flag_emoji' => '🇹🇭',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Timor-Leste',
                    'ar' => 'تيمور الشرقية',
                ],
                'iso_alpha_2' => 'TL',
                'iso_alpha_3' => 'TLS',
                'dial_code' => '+670',
                'currency_code' => 'USD',
                'flag_emoji' => '🇹🇱',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Togo',
                    'ar' => 'توغو',
                ],
                'iso_alpha_2' => 'TG',
                'iso_alpha_3' => 'TGO',
                'dial_code' => '+228',
                'currency_code' => 'XOF',
                'flag_emoji' => '🇹🇬',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Tonga',
                    'ar' => 'تونغا',
                ],
                'iso_alpha_2' => 'TO',
                'iso_alpha_3' => 'TON',
                'dial_code' => '+676',
                'currency_code' => 'TOP',
                'flag_emoji' => '🇹🇴',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Trinidad and Tobago',
                    'ar' => 'ترينيداد وتوباغو',
                ],
                'iso_alpha_2' => 'TT',
                'iso_alpha_3' => 'TTO',
                'dial_code' => '+1-868',
                'currency_code' => 'TTD',
                'flag_emoji' => '🇹🇹',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Tunisia',
                    'ar' => 'تونس',
                ],
                'iso_alpha_2' => 'TN',
                'iso_alpha_3' => 'TUN',
                'dial_code' => '+216',
                'currency_code' => 'TND',
                'flag_emoji' => '🇹🇳',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Turkey',
                    'ar' => 'تركيا',
                ],
                'iso_alpha_2' => 'TR',
                'iso_alpha_3' => 'TUR',
                'dial_code' => '+90',
                'currency_code' => 'TRY',
                'flag_emoji' => '🇹🇷',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Turkmenistan',
                    'ar' => 'تركمانستان',
                ],
                'iso_alpha_2' => 'TM',
                'iso_alpha_3' => 'TKM',
                'dial_code' => '+993',
                'currency_code' => 'TMT',
                'flag_emoji' => '🇹🇲',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Tuvalu',
                    'ar' => 'توفالو',
                ],
                'iso_alpha_2' => 'TV',
                'iso_alpha_3' => 'TUV',
                'dial_code' => '+688',
                'currency_code' => 'AUD',
                'flag_emoji' => '🇹🇻',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Uganda',
                    'ar' => 'أوغندا',
                ],
                'iso_alpha_2' => 'UG',
                'iso_alpha_3' => 'UGA',
                'dial_code' => '+256',
                'currency_code' => 'UGX',
                'flag_emoji' => '🇺🇬',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Ukraine',
                    'ar' => 'أوكرانيا',
                ],
                'iso_alpha_2' => 'UA',
                'iso_alpha_3' => 'UKR',
                'dial_code' => '+380',
                'currency_code' => 'UAH',
                'flag_emoji' => '🇺🇦',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'United Arab Emirates',
                    'ar' => 'الإمارات',
                ],
                'iso_alpha_2' => 'AE',
                'iso_alpha_3' => 'ARE',
                'dial_code' => '+971',
                'currency_code' => 'AED',
                'flag_emoji' => '🇦🇪',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'United Kingdom',
                    'ar' => 'المملكة المتحدة',
                ],
                'iso_alpha_2' => 'GB',
                'iso_alpha_3' => 'GBR',
                'dial_code' => '+44',
                'currency_code' => 'GBP',
                'flag_emoji' => '🇬🇧',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'United States',
                    'ar' => 'الولايات المتحدة',
                ],
                'iso_alpha_2' => 'US',
                'iso_alpha_3' => 'USA',
                'dial_code' => '+1',
                'currency_code' => 'USD',
                'flag_emoji' => '🇺🇸',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Uruguay',
                    'ar' => 'أوروغواي',
                ],
                'iso_alpha_2' => 'UY',
                'iso_alpha_3' => 'URY',
                'dial_code' => '+598',
                'currency_code' => 'UYU',
                'flag_emoji' => '🇺🇾',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Uzbekistan',
                    'ar' => 'أوزبكستان',
                ],
                'iso_alpha_2' => 'UZ',
                'iso_alpha_3' => 'UZB',
                'dial_code' => '+998',
                'currency_code' => 'UZS',
                'flag_emoji' => '🇺🇿',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Vanuatu',
                    'ar' => 'فانواتو',
                ],
                'iso_alpha_2' => 'VU',
                'iso_alpha_3' => 'VUT',
                'dial_code' => '+678',
                'currency_code' => 'VUV',
                'flag_emoji' => '🇻🇺',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Vatican City',
                    'ar' => 'الفاتيكان',
                ],
                'iso_alpha_2' => 'VA',
                'iso_alpha_3' => 'VAT',
                'dial_code' => '+379',
                'currency_code' => 'EUR',
                'flag_emoji' => '🇻🇦',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Venezuela',
                    'ar' => 'فنزويلا',
                ],
                'iso_alpha_2' => 'VE',
                'iso_alpha_3' => 'VEN',
                'dial_code' => '+58',
                'currency_code' => 'VES',
                'flag_emoji' => '🇻🇪',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Vietnam',
                    'ar' => 'فيتنام',
                ],
                'iso_alpha_2' => 'VN',
                'iso_alpha_3' => 'VNM',
                'dial_code' => '+84',
                'currency_code' => 'VND',
                'flag_emoji' => '🇻🇳',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Yemen',
                    'ar' => 'اليمن',
                ],
                'iso_alpha_2' => 'YE',
                'iso_alpha_3' => 'YEM',
                'dial_code' => '+967',
                'currency_code' => 'YER',
                'flag_emoji' => '🇾🇪',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Zambia',
                    'ar' => 'زامبيا',
                ],
                'iso_alpha_2' => 'ZM',
                'iso_alpha_3' => 'ZMB',
                'dial_code' => '+260',
                'currency_code' => 'ZMW',
                'flag_emoji' => '🇿🇲',
                'is_active' => false,
            ],
            [
                'name' => [
                    'en' => 'Zimbabwe',
                    'ar' => 'زيمبابوي',
                ],
                'iso_alpha_2' => 'ZW',
                'iso_alpha_3' => 'ZWE',
                'dial_code' => '+263',
                'currency_code' => 'ZWL',
                'flag_emoji' => '🇿🇼',
                'is_active' => false,
            ],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['iso_alpha_2' => $country['iso_alpha_2']],
                $country
            );
        }
    }
}
